### ISSUE TITLE
stand-alone operation

### ISSUE THREAD

**Issue by jordens** [m-labs/sayma#10]
* How is DRTIO wired up without an AMC backplane or Metlino? SATA? Media converters? SFP?
* How should the clocks get onto the RTM without an rf backplane?
* How is the RTM powered?

@jbqubit, @gkasprow

**Comment by gkasprow** [comment]
We will use very simple AMC to SFP converter adapter which can be optionally installed inside of simple mechanical box.
Clock will get to the RTM directly, via SMA connector on its front (rear) panel
RTM is powered from Sayma AMC or via RF backplane

**Comment by jordens** [comment]
Ok.
