### ISSUE TITLE
fpga speed grade

### ISSUE THREAD

**Issue by jordens** [m-labs/sayma#18]
Kintex Ultrascale -1 or -2 choice for price.

The only relevant difference that I can see right now is: (http://www.xilinx.com/support/documentation/data_sheets/ds892-kintex-ultrascale-data-sheet.pdf)

* CPLL on -1 is 8.5 G max. That's not a problem for the 16 DAC TX GTH, but for the 4 SFP/SATA/AMC GTH TX they would need to be driven from the same QPLL if we want to run them faster than 8.5 G.

@sbourdeauducq ok to choose -1 speed grade for price?

**Comment by sbourdeauducq** [comment]
Ok.

**Comment by jbqubit** [comment]
@gkasprow please update when you know the price from Xilinx.

**Comment by jordens** [comment]
@jbqubit update what?
AFAICS This is decided.

**Comment by jbqubit** [comment]
Agreed that this is decided to use -1 speed grade. @gkasprow is checking on price per chip which I hope he will post here.

**Comment by jordens** [comment]
XCKU040-1FFVA1156C
