### ISSUE TITLE
debug connector

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/sayma#31]
I propose a simple 2.54mm 3.3V header that can be connected to a USB/Serial adapter for basic debugging tasks. Just two wires (rx/tx, plus ground) would be enough.

**Comment by sbourdeauducq** [comment]
And should we have a direct a JTAG connector on the board or will this go through standard MicroTCA pins (only)?

**Comment by jordens** [comment]
IIRC in Warsaw we wanted to slap a 4 channel FTDI thing on there with the channels doing (a) fpga jtag (b) fpga console (c), (d) doing some MTC stuff. That gets rid of having to find usb serial adapters and jtag adapters, it can be exposed on the panel, and it is a nicer connector.

**Comment by sbourdeauducq** [comment]
OK, that would be fine too.

**Comment by gkasprow** [comment]
I always place some header with IO pins around FPGA for debugging purposes :)

**Comment by gkasprow** [comment]
I  placed standard Xilinx JTAG connector on board for ones who want to use standard Xilinx cable.

**Comment by jordens** [comment]
sounds fine. i don't think we will touch that if we have the ftdi interface.
